version: '3.8'

services:
  db:
    image: mariadb:11
    container_name: gourmet_db
    restart: always
    environment:
      MARIADB_DATABASE: gourmet_saudavel
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - gourmet_network
    volumes:
      - gourmet_data:/var/lib/mysql

  # ✅ ADICIONADO: Redis para gerenciar a fila BullMQ
  redis:
    image: redis:alpine
    container_name: gourmet_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - gourmet_network
    command: ["redis-server", "--appendonly", "yes"]

  adminer:
    image: adminer
    container_name: gourmet_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - gourmet_network

networks:
  gourmet_network:

volumes:
  gourmet_data: